# xarm:
# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 250

# Position Controllers ---------------------------------------
joint1_position_controller:
  type: position_controllers/JointPositionController
  joint: joint1
  pid: {p: 1200.0, i: 5.0, d: 10.0}
joint2_position_controller:
  type: position_controllers/JointPositionController
  joint: joint2
  pid: {p: 1400.0, i: 5.0, d: 10.0}
joint3_position_controller:
  type: position_controllers/JointPositionController
  joint: joint3
  pid: {p: 1200.0, i: 5.0, d: 5.0}
joint4_position_controller:
  type: position_controllers/JointPositionController
  joint: joint4
  pid: {p: 850.0, i: 3.0, d: 5.0}
joint5_position_controller:
  type: position_controllers/JointPositionController
  joint: joint5
  pid: {p: 500.0, i: 3.0, d: 1.0}
joint6_position_controller:
  type: position_controllers/JointPositionController
  joint: joint6
  pid: {p: 500.0, i: 1.0, d: 1.0}
joint7_position_controller:
  type: position_controllers/JointPositionController
  joint: joint7
  pid: {p: 300.0, i: 0.05, d: 1.0}

joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
     - joint1
     - joint2
     - joint3
     - joint4
     - joint5
     - joint6
     - joint7
     
  pid_gains:  
    joint_1: {p: 1200.0, i: 5.0, d: 10.0}
    joint_2: {p: 1400.0, i: 5.0, d: 10.0}
    joint_3: {p: 1200.0, i: 5.0, d: 5.0}
    joint_4: {p: 850.0, i: 3.0, d: 5.0}
    joint_5: {p: 500.0, i: 3.0, d: 1.0}
    joint_6: {p: 500.0, i: 1.0, d: 1.0}
    joint_7: {p: 300.0, i: 0.05, d: 1.0}
# No Pid gains specified error fix
# gazebo_ros_control:
#   pid_gains:
#     joint1: {p: 1200.0, i: 5.0, d: 10.0}
#     joint2: {p: 1400.0, i: 5.0, d: 10.0}
#     joint3: {p: 1200.0, i: 5.0, d: 5.0}
#     joint4: {p: 850.0, i: 3.0, d: 5.0}
#     joint5: {p: 500.0, i: 3.0, d: 1.0}
#     joint6: {p: 500.0, i: 1.0, d: 1.0}
#     joint7: {p: 300.0, i: 0.05, d: 1.0}

